import './globals.css'
import Navbar from "@/components/Navbar"
import {Toaster} from "react-hot-toast"
export const metadata = {
  title: 'CodeHosp',
  description: 'Generated by Next.js',
}


export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <head>
        <link rel="icon" href="/logo3.png" />
      </head>
      <body>
        <Navbar />
        <Toaster position="top-right" />
        {children}
      </body>
    </html>
  )
}
